theme: minima
skin: classic
title: Maayen
author: Conrad Maaijen
email: conrad@maayen.nl
description: > # this means to ignore newlines until "show_excerpts:"
  Conrad Maaijen is a Laravel enthusiast and PHP developer at Osec B.V.
  You find also a lot of snippets, also used for self-reference.
show_excerpts: true
excerpt_separator: <!--more-->
minima:
 date_format: "%d-%m-%Y"
 social_links:
    github:  conradmaaijen
    twitter: conradmaayen
    telegram:  conradmaayen

header_pages:
  - index.md
  - about.md
  - uses.md
  - site-index.md
